### ISSUE TITLE
Failed to build the buildroot

### ISSUE THREAD

**Issue by FantasyJXF** [rockchip-linux/buildroot#9]
I had successfully built the kernel and u-boot for with target RK3399 board.

But I get stuck build the buildroot.

The wrong msg are as follows:
```
/usr/bin/make -j1 O=/home/fantasy/repo/buildroot/output/rockchip_rk3399 HOSTCC="/usr/lib/ccache/gcc" HOSTCXX="/usr/lib/ccache/g++" silentoldconfig
  GEN     /home/fantasy/repo/buildroot/output/rockchip_rk3399/Makefile
>>> host-libxcb 1.12 Building
PATH="/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/bin:/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/sbin:/usr/local/cuda-8.0/bin:/opt/ros/kinetic/bin:/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/bin:/usr/lib/ccache:/home/fantasy/ninja:/opt/gcc-arm-none-eabi-5_4-2016q2/bin:/home/fantasy/bin:/home/fantasy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" PKG_CONFIG="/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/bin/pkg-config" PKG_CONFIG_SYSROOT_DIR="/" PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_LIBDIR="/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/pkgconfig:/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/share/pkgconfig"  /usr/bin/make -j9  -C /home/fantasy/repo/buildroot/output/rockchip_rk3399/build/host-libxcb-1.12/
Making all in src
  GEN      xproto.c
  GEN      bigreq.c
  GEN      xc_misc.c
  GEN      composite.c
  GEN      damage.c
  GEN      dpms.c
  GEN      dri2.c
  GEN      dri3.c
  GEN      present.c




Failed to load the xcbgen Python package!
Failed to load the xcbgen Python package!
Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
Make sure that xcb/proto installed it on your Python path.
Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
If not, you will need to create a .pth file or define $PYTHONPATH
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
to extend the path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
to extend the path.
Refer to the README file in xcb/proto for more info.
Refer to the README file in xcb/proto for more info.
Refer to the README file in xcb/proto for more info.
Refer to the README file in xcb/proto for more info.





Failed to load the xcbgen Python package!
Traceback (most recent call last):
  File "./c_client.py", line 3294, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "./c_client.py", line 3294, in <module>
Make sure that xcb/proto installed it on your Python path.
  File "./c_client.py", line 3294, in <module>
If not, you will need to create a .pth file or define $PYTHONPATH
Traceback (most recent call last):
to extend the path.
Refer to the README file in xcb/proto for more info.

  File "./c_client.py", line 3294, in <module>
Traceback (most recent call last):
  File "./c_client.py", line 3294, in <module>
        from xcbgen.state import Module
from xcbgen.state import Module
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>
      File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>
from xcbgen.state import Module
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>

Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
Refer to the README file in xcb/proto for more info.

Traceback (most recent call last):
  File "./c_client.py", line 3294, in <module>
    from xml.etree.cElementTree import parse
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from xml.etree.cElementTree import parse
    from xcbgen.state import Module
      File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
from xcbgen.state import Module
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>
    from xml.etree.cElementTree import parse
    from xml.etree.cElementTree import parse
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
                from _elementtree import *
from _elementtree import *
from _elementtree import *
from _elementtree import *
ImportErrorImportErrorImportErrorImportError: : : /home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat: /home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat
/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat


    from xcbgen.state import Module
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>
    from xml.etree.cElementTree import parse
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: /home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat

Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
Refer to the README file in xcb/proto for more info.

Traceback (most recent call last):
  File "./c_client.py", line 3294, in <module>
    from xcbgen.state import Module
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>
    from xml.etree.cElementTree import parse
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: /home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat

Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
Refer to the README file in xcb/proto for more info.

Traceback (most recent call last):
  File "./c_client.py", line 3294, in <module>
    from xcbgen.state import Module
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>
    from xml.etree.cElementTree import parse
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: /home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat
    from xml.etree.cElementTree import parse
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: /home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat
Makefile:1290: recipe for target 'xc_misc.c' failed
make[3]: *** [xc_misc.c] Error 1
make[3]: *** Waiting for unfinished jobs....
Makefile:1290: recipe for target 'damage.c' failed
make[3]: *** [damage.c] Error 1
Makefile:1290: recipe for target 'dpms.c' failed
make[3]: *** [dpms.c] Error 1
Makefile:1290: recipe for target 'dri3.c' failed
make[3]: *** [dri3.c] Error 1
Makefile:1290: recipe for target 'dri2.c' failed
make[3]: *** [dri2.c] Error 1
Makefile:1290: recipe for target 'present.c' failed
make[3]: *** [present.c] Error 1
Makefile:1290: recipe for target 'bigreq.c' failed
make[3]: *** [bigreq.c] Error 1
Makefile:1290: recipe for target 'composite.c' failed
make[3]: *** [composite.c] Error 1

Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
Refer to the README file in xcb/proto for more info.

Traceback (most recent call last):
  File "./c_client.py", line 3294, in <module>
    from xcbgen.state import Module
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/state.py", line 5, in <module>
    from xml.etree.cElementTree import parse
  File "/home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: /home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/lib-dynload/_elementtree.so: undefined symbol: PyUnicodeUCS2_FromFormat
Makefile:1290: recipe for target 'xproto.c' failed
make[3]: *** [xproto.c] Error 1
Makefile:788: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
package/pkg-generic.mk:247: recipe for target '/home/fantasy/repo/buildroot/output/rockchip_rk3399/build/host-libxcb-1.12/.stamp_built' failed
make[1]: *** [/home/fantasy/repo/buildroot/output/rockchip_rk3399/build/host-libxcb-1.12/.stamp_built] Error 2
Makefile:83: recipe for target '_all' failed
make: *** [_all] Error 2

```

AND I did have xbcgen Python package:
```
Help on package xcbgen:

NAME
    xcbgen

FILE
    /home/fantasy/repo/buildroot/output/rockchip_rk3399/host/lib/python2.7/site-packages/xcbgen/__init__.py

PACKAGE CONTENTS
    align
    error
    expr
    matcher
    state
    xtypes

```

**Comment by Caesar-github** [comment]
It seem need install some packages for your PC.

For example, the buildroot depend on the following packages.

sudo apt-get install repo git-core gitk git-gui gcc-arm-linux-gnueabihf u-boot-tools device-tree-
compiler gcc-aarch64-linux-gnu mtools parted libudev-dev libusb-1.0-0-dev python-linaro-image-
tools linaro-image-tools autoconf autotools-dev libsigsegv2 m4 intltool libdrm-dev curl sed make
binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio python unzip rsync file bc wget
libncurses5 libqt4-dev libglib2.0-dev libgtk2.0-dev libglade2-dev cvs git mercurial rsync openssh-
client subversion asciidoc w3m dblatex graphviz python-matplotlib libc6:i386 libssl-dev texinfo
liblz4-tool genext2fs

**Comment by FantasyJXF** [comment]
Thanks, I'm going to try this
